name: Get latest release etcd-workbench version
on:
  workflow_dispatch:

  schedule:
    - cron:  '0 0,6,12,18 * * *'
jobs:
  osx-app-to-homebrew:
    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v2

      - name: Fetch latest release version
        id: fetch_version
        run: |
          latest_version=$(curl -sL -I -o /dev/null -w "%{url_effective}" https://github.com/tzfun/etcd-workbench/releases/latest | xargs basename | cut -d '-' -f 2)
          if [ -z "$latest_version" ] || [ "$latest_version" == "null" ]; then
            echo "Failed to fetch latest version from GitHub API."
            exit 1
          fi
          echo "latest_version=$latest_version" >> $GITHUB_ENV

      - name: Get current version from etcd-workbench.rb
        id: current_version
        run: |
          current_version=$(grep 'version ' ./Casks/etcd-workbench.rb | cut -d '"' -f 2)
          echo "current_version=$current_version" >> $GITHUB_ENV

      - name: Compare versions
        id: version_check
        run: |
          if [ "$latest_version" != "$current_version" ]; then
            echo "Versions differ. Proceeding with action."
            echo "new_version_found=true" >> $GITHUB_ENV
          else
            echo "Versions are the same. No action needed."
            echo "new_version_found=false" >> $GITHUB_ENV
          fi

      - name: Release to Homebrew Private Tap
        if: env.new_version_found == 'true'
        env:
          VERSION: ${{ env.latest_version }}
        id: homebrew-releaser

        run: |
          brew tap ttdjong/homebrew-etcd-workbench
          brew bump-cask-pr --no-fork --version $VERSION --no-browse --message "Update Etcd Workbench to version $VERSION" --write-only --commit etch-workbench
          git remote add local-other /opt/homebrew/Library/Taps/ttdjong/homebrew-etcd-workbench
          git fetch local-other
          git reset --hard local-other/main
          git status
          git push origin
